Models/ErrorViewModel.cs
using System;

namespace StickyNotes.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Notes.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace StickyNotes.Models
{
    public class Notes
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
    }
}

Models/SeedData.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using StickyNotes.Data;
using System;
using System.Linq;

namespace StickyNotes.Models
{
    public static class SeedData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new StickyNotesContext(
                serviceProvider.GetRequiredService<
                    DbContextOptions<StickyNotesContext>>()))
            {
                // Look for any Notes.
                if (context.Note.Any())
                {
                    return;   // DB has been seeded
                }

                context.Note.AddRange(
                    new Notes
                    {
                        Title = "Note Numba 1",
                        Text = "What it do boo"
                    }
                );
                context.SaveChanges();
            }
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StickyNotes.Models;

namespace Home.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }



        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/StickyNotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StickyNotes.Data;
using StickyNotes.Models;

namespace StickyNotes.Controllers
{
    public class StickyNotesController : Controller
    {
        private readonly StickyNotesContext _context;

        public StickyNotesController(StickyNotesContext context)
        {
            _context = context;
        }

        // GET: StickyNotes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Note.ToListAsync());
        }

        // GET: StickyNotes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var notes = await _context.Note
                .FirstOrDefaultAsync(m => m.Id == id);
            if (notes == null)
            {
                return NotFound();
            }

            return View(notes);
        }

        // GET: StickyNotes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: StickyNotes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Text")] Notes notes)
        {
            if (ModelState.IsValid)
            {
                _context.Add(notes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(notes);
        }

        // GET: StickyNotes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var notes = await _context.Note.FindAsync(id);
            if (notes == null)
            {
                return NotFound();
            }
            return View(notes);
        }

        // POST: StickyNotes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Text")] Notes notes)
        {
            if (id != notes.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(notes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NotesExists(notes.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(notes);
        }

        // GET: StickyNotes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var notes = await _context.Note
                .FirstOrDefaultAsync(m => m.Id == id);
            if (notes == null)
            {
                return NotFound();
            }

            return View(notes);
        }

        // POST: StickyNotes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var notes = await _context.Note.FindAsync(id);
            _context.Note.Remove(notes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // public IActionResult Board()
        // {
        //     return View();
        // } 
        public async Task<IActionResult> Board()
        {
            return View(await _context.Note.ToListAsync());
        }

        private bool NotesExists(int id)
        {
            return _context.Note.Any(e => e.Id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@* Index of view home *@

<h2>Index</h2>

<p>Hello from our View Template!</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StickyNotesApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="StickyNotes" asp-action="Index">StickyNotesApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StickyNotes" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StickyNotes" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - StickyNotesApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<script>
</script>

Views/StickyNotes/Board.cshtml
@model IEnumerable<StickyNotes.Models.Notes>

<button onclick="newCol()">new col</button>
<a href='/stickynotes/board'><button onclick='resetLocs()'>Reset</button></a>
@* <div class="all-slides" >
    <div id="sticky0" class="box" >idk jus seein what shows up and where it goes and if it wraps or idk is it jus gona mess up like usual or blah some more blah</div>
    <div id="sticky1" class="box" >bLH blah</div>
</div> *@

@* <table>
    <tr id="column">
        <th>col1</th>
        <th>col2</th>
        <th>col3</th>
        <th>col4</th>
    </tr>
    <tr>
        <td class="contain">
        <div id="sticky3" class="box" >idk jus seein what shows up and where it goes and if it wraps or idk is it jus gona mess up like usual or blah some more blah</div>
        </td>
        <td class="contain">
        <div id="sticky0" class="box" >idk jus seein what shows up and where it goes and if it wraps or idk is it jus gona mess up like usual or blah some more blah</div>
        </td>
        <td class="contain">
        <div id="sticky1" class="box" >bLH blah</div>
        </td>
    </tr>
</table> *@

@{int c = 0;}
@{int i = 9;}
<table>
    <tr id='head'>
        @foreach (var col in Model)
        {
            <th id='@("column" + c.ToString())'> @col.Title </th>
            c++;
        }
        <th>col2</th>
        <th>col3</th>
        <th>col4</th>
    </tr>
    <tr>
        @foreach (var note in Model)
        {
            <td>
            <div id= '@("sticky" + i.ToString())' class="box">@note.Title <br> @note.Text</div>
            </td>
            i++;
        }
    </tr>
    <tr>
    </tr>
</table>

@* @{int i = 9;}
@foreach (var note in Model)
{
    <div id= '@("sticky" + i.ToString())' class="box">@note.Title <br> @note.Text</div>
    i++;
} *@


@* @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Text)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table> *@


<script>
    var sPositions = localStorage.positions || "{}",
    positions = JSON.parse(sPositions);
    console.log(positions)
    $.each(positions, function (id, pos) {$("#" + id).css(pos)})

    for (let y = 0; y <= 12; y++) {
        $("#sticky"+y).draggable({
        grid: [ 280, 280 ],
        containment: "#containment-wrapper",
        scroll: false,
        stop: function (event, ui) {positions[this.id] = ui.position 
        localStorage.positions = JSON.stringify(positions)}
    });
    }

    function resetLocs() {
        localStorage.positions = "";
    }

    function newCol() { 
        document.getElementById("head").innerHTML += "<th>what it do</th>"; //$ dont work fix later
        @* var whatItSays = document.getElementById("input").value; *@
        @* document.getElementById("sticky"+i).innerHTML = whatItSays; *@
        @* i++; *@
    }
</script>
<style>
    th {
        width: 280px;
        text-align: center;
    }
    td {
        
    }
    html {
        left: 0;
    }
    .grid {
        @* width: 93em; *@
        @* margin-left: 33em; *@
        @* margin-top: -15em; *@
    }
    .contain{width: 280px; height: 280px;}
    .box {
        position: relative;
        float: left;
        height: 250px;
        width: 250px;
        background-color: yellow;
        border: 2px solid black;
        padding: 15px;
        @* margin-left: 5.6em; *@
        transform:rotate(-3deg);
    }
</style>

Views/StickyNotes/Create.cshtml
@model StickyNotes.Models.Notes

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Notes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/StickyNotes/Delete.cshtml
@model StickyNotes.Models.Notes

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Notes</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/StickyNotes/Details.cshtml
@model StickyNotes.Models.Notes

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Notes</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/StickyNotes/Edit.cshtml
@model StickyNotes.Models.Notes

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Notes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/StickyNotes/Index.cshtml
@model IEnumerable<StickyNotes.Models.Notes>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Text)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Text)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>